### ISSUE TITLE
Fix internal CI failures and add OV unit tests

### ISSUE THREAD

**Issue by jarcherNV** [shader-slang/slang#7547]
Our internal CI has been failing for a few months now. This task is to address the failures and get it into a working state, then add OV unit tests so we can catch failures before they do.

**Comment by jarcherNV** [comment]
I have created this task here rather than in gitlab for easier tracking. OV has reported additional failures after we addressed the previous ones so Kai thinks it may be better to now fix our internal CI and add their failing unit tests to it so we can catch them ourselves.

**Comment by gtong-nv** [comment]
Update:
The original issues blocking OV have been root caused and fixes pending.
There is 1 remaining issue filed last week. Once that resolved we should be able to add the unit tests.

**Comment by gtong-nv** [comment]
A linux failure has been reported and tracked in https://github.com/shader-slang/slang/issues/8296

**Comment by gtong-nv** [comment]
I think we can close this as all the regression that blocks OV from using the latest Slang has been resolved, and the nightly regression has been enabled in internel gitlab.
What's remaining is the new separated debug symbol feature is still not completed, and causing the coressponding unit test to be failed.
The issue will be addressed as part of https://github.com/shader-slang/slang/issues/8295
