### ISSUE TITLE
Slang crashing when finding exported decls from precompiled modules

### ISSUE THREAD

**Issue by AlpyneDreams** [shader-slang/slang#8880]
# Issue Description
Similar to #8849 I am getting a crash when using precompiled modules. Specifically slang crashes [at this line in `ASTSerialReadContext::_readImportedDecl`](https://github.com/shader-slang/slang/blob/361bd2801ead62b24987774dd2fc7940ee39eee5/source/slang/slang-serialize-ast.cpp#L1732) in a call to `loadModule`. No error message is returned.

# Reproducer Code
Unfortunately I am not able to reproduce this issue with `slangc`, I can only get it to happen when using the API, and I am not able to provide a dump file that uses public debug info because the latest release does not include the fix to #8849 so I would get a different crash and wouldn't be able to reproduce this new crash. I will try to provide a dump file as soon as new debug infos are available.

Here is everything else I can provide:
- [Full shader sources including all the slang-module files](https://github.com/user-attachments/files/23270064/core.zip)
  - Specifically I am compiling `clustered/cluster_cull.slang` but I think this will happen with other shaders too.
  - The slang-module files are in a separate folder to the slang files, but putting them in the same folder doesn't seem to help.
 - [Shader compiler C++ code](https://github.com/user-attachments/files/23270177/ShaderCompiler.cpp.txt)
   - This contains all of my compiler settings.

And here is a screenshot of the callstack of the crash:
<img width="800" alt="Stack trace screenshot" src="https://github.com/user-attachments/assets/f685ae5e-ceb4-4730-808d-33cfbfdcf483" />

# Expected Behavior
I would expect that slang can do whatever it needs to load the module. At the very least, I would expect an error message and a graceful failure instead of an unhandled exception.

# Actual Behavior
Slang crashes [at this line in `ASTSerialReadContext::_readImportedDecl`](https://github.com/shader-slang/slang/blob/361bd2801ead62b24987774dd2fc7940ee39eee5/source/slang/slang-serialize-ast.cpp#L1732). No error message is returned.

# Environment
- Slang Version v2025.18.1
- OS Windows 11
- NVIDIA RTX 3080 Ti Laptop GPU, Driver Version 576.88

**Comment by csyonghe** [comment]
@AlpyneDreams can you clarify if this is reproducible with #8849 applied?

**Comment by csyonghe** [comment]
This seems very tricky to reproduce.

PR#8884 attempts to generate a graceful error message. But I think the fact we are hitting that line is a bug in itself. The only reason I can think of that we will ever hit that line is the precompiled module is out of date. If this is not the case then it is a slang bug.

In order to reproduce this and debug on my end, I will need a precompiled binary of your app along with all the files it needs so that I can run the application locally. 

It would be also helpful if you can try PR 8884 and let me know what behavior you are seeing with the tentative fixes there.

**Comment by AlpyneDreams** [comment]
> @AlpyneDreams can you clarify if this is reproducible with #8849 applied?

With the fix for the issue #8849, this error is reproducible. Without the fix, it probably would still occur, but I get the error caused by issue #8849 before it can ever happen.

**Comment by AlpyneDreams** [comment]
> This seems very tricky to reproduce.
> 
> PR#8884 attempts to generate a graceful error message. But I think the fact we are hitting that line is a bug in itself. The only reason I can think of that we will ever hit that line is the precompiled module is out of date. If this is not the case then it is a slang bug.
> 
> In order to reproduce this and debug on my end, I will need a precompiled binary of your app along with all the files it needs so that I can run the application locally. 
> 

Unfortunately I can't easily distribute my whole app, it's a 20 GB game and we can't really release copies of it while it's not done. It might be possible to strip it down to just the essential files but it would be complicated.

What I can try to do soon is probably build slang myself and give you that build with PDBs and a dump file so you can see what's going on better.

**Comment by AlpyneDreams** [comment]
> It would be also helpful if you can try PR 8884 and let me know what behavior you are seeing with the tentative fixes there.

I'll see if this PR helps when I do my next test soon.

**Comment by AlpyneDreams** [comment]
@csyonghe When running with #8884 I don't get a crash but I do get the following error:
```
[Slang] Failed to compile shader shader 'legacy/hbao', diagnostics:
(0): error 1: cannot open file 'attrs.slang'.
(0): error 15301: failed to find imported file 'attrs'
(0): error 1: cannot open file 'math.slang'.
(0): error 15301: failed to find imported file 'math'
(0): error 1: cannot open file 'fog.slang'.
(0): error 15301: failed to find imported file 'fog'
```

I assume this is probably because I am using relative imports (for example `import math` instead of `import common.math` in modules that are in the `common` folder). I went through and changed all my shaders to use absolute imports like `import common.math` (although I think this shouldn't be necessary?) and now I am getting a new crash in `findGlobalHashedStringLiterals` (under `getEntryPointCode`).

Here is [a dump file](https://alpyne.me/upload/slang-crash-pr-8884.zip) with the DLLs and PDBs I compiled with #8884 applied so that you can debug it (you might have to point VS to the source files).

**Comment by csyonghe** [comment]
@AlpyneDreams Is the dump a debug build? It appears that one of the loaded modules (`legacy/hbao`) has the AST part but not the IR part, suggesting that the loading of the module isn't fully successful. If this was a debug build, there is an `assert` that should have been triggered earlier. I do not understand why the load of the IR failed.

I have updated the PR and hope we can get more useful info this time. Can you try the updated PR with a debug build?
Specifically, I would like to know if `slang\slang-serialize-ir.cpp:840` ever hit, and why that is the case if it does hit and all modules are up to date.

**Comment by AlpyneDreams** [comment]
> @AlpyneDreams Is the dump a debug build? It appears that one of the loaded modules (`legacy/hbao`) has the AST part but not the IR part, suggesting that the loading of the module isn't fully successful. If this was a debug build, there is an `assert` that should have been triggered earlier. I do not understand why the load of the IR failed.
> 
> I have updated the PR and hope we can get more useful info this time. Can you try the updated PR with a debug build?
> Specifically, I would like to know if `slang\slang-serialize-ir.cpp:840` ever hit, and why that is the case if it does hit and all modules are up to date.

I'll try to get one with a debug build as soon as I can.

**Comment by AlpyneDreams** [comment]
@csyonghe  I have built a debug build with #8884 as of 2ab0075ee321c1d12f3597662aa99485c88eeaf8 and reproduced the issue again.

For this test I have set `UseUpToDateBinaryModule` to 0 so that it can't just ignore the slang-modules.

Now, regardless of whether I use absolute or relative imports, slang crashes in `findGlobalHashedStringLiterals` due to a null IR module.

Here is [a zip with the crash dump](https://alpyne.me/upload/slang-crash-pr-8884-2.zip), debug DLLs and PDBs I compiled (as of 2ab0075ee321c1d12f3597662aa99485c88eeaf8, not 95db02272e53688cad72e8aa19d4e0a3f574b15d), and the .slang-module files that were generated. The source files are mostly the same as already posted, but I made all imports absolute relative to the slang dir as described above.

**Comment by AlpyneDreams** [comment]
@csyonghe Any updates on this? Let me know if there's anything else you need. I have provided a new dump with PDBs and shader source files above. The issue is still present as of v2025.23.1. Not being able to use module caching is really hurting my iteration times.

**Comment by AlpyneDreams** [comment]
Just tested in v2025.23.1 and can confirm the issue still persists with the crash in `findGlobalHashedStringLiterals`.

This follows an error message that was added in 6082defeecbfab46a81b5b2c3579ce939623a1c3:
```
(0): error 15303: cannot resolve imported declaration '_S5attrs7Sampler' from precompiled module 'common/attrs'. Make sure module 'common/attrs' is up-to-date. If you suspect this to be a compiler bug, file an issue on GitHub (https://github.com/shader-slang/slang/issues) or join the Slang Discord for assistance
```
I am not sure if this error is related to the actual cause of the crash though.

Here is a [new dump file + shader sources + shader module files](https://alpyne.me/upload/slang-crash-v2025.23.1.zip) made with the latest DLLs and PDBs from the releases page for slang v2025.23.1.

- The shader in question was `legacy/hbao` (it compiles after `clustered/cluster_create`)
- `UseUpToDateBinaryModules` was disabled otherwise slang appears to always ignore the modules and recompiles from source files

**Comment by bmillsNV** [comment]
@aidanfnv wondering if you can repro and debug this?

**Comment by AlpyneDreams** [comment]
I've been able to reproduce this issue on the command line using Slang 2025.23.2 with a very simple repro. Here are the steps:

<details>
<summary><code>test.slang</code></summary>

```slang
module test;
import foo;

[Texture("myTextureName")]
RWTexture2D texture;

[numthreads(1, 1, 1)]
void main(uint3 idx: SV_DispatchThreadID)
{
    texture[idx.xy] = float4(1, 0, 0, 1);
}
```

</details>
<details>
<summary><code>foo.slang</code></summary>

```slang
module foo;

[__AttributeUsage(_AttributeTargets.Var)]
public struct TextureAttribute
{
    string name;
};
```

</details>

Steps:
1. Run `slangc -o test.slang-module test.slang`
2. Observe `test.slang-module` is generated
3. Run `slangc -o test.spv-asm test.slang-module`
4. Observe the following error:
```
(0): error 15303: cannot resolve imported declaration '_S3foo7Texture' from precompiled module 'foo'. Make sure module 'foo' is up-to-date. If you suspect this to be a compiler bug, file an issue on GitHub (https://github.com/shader-slang/slang/issues) or join the Slang Discord for assistance
```

Notes:
- It does not matter if `foo.slang` is precompiled into a `.slang-module` or not, the result is always the same.
- Notably using the source file instead of the module with `slangc -o test.spv-asm test.slang` works fine, but it fails with the precompiled module

**Comment by csyonghe** [comment]
Thank you for providing us this repo, this is extremely helpful. We will investigate and provide further updates here.

**Comment by csyonghe** [comment]
While I can reproduce the issue with the `slangc` commandline, this isn't reproducible with the compilation API. Here's the API call I tested for your reference.

```
// unit-test-precompiled-module-attribute.cpp

// Test loading a precompiled module that defines a user defined attribute.

#include "core/slang-io.h"
#include "core/slang-memory-file-system.h"
#include "slang-com-ptr.h"
#include "slang.h"
#include "unit-test/slang-unit-test.h"

#include <stdio.h>
#include <stdlib.h>

using namespace Slang;

// Test loading a precompiled module that imports other modules.
SLANG_UNIT_TEST(precompiledModuleWithUserDefinedAttribute)
{
    // Prepare the virtual file system with the module files.
    const char* fooSource = R"(
        module foo;
        [__AttributeUsage(_AttributeTargets.Var)]
        public struct TextureAttribute
        {
            string name;
        };
    )";
    const char* testSource = R"(
        module test;
        import foo;

        [Texture("myTextureName")]
        RWTexture2D texture;

        [numthreads(1, 1, 1)]
        void computeMain(uint3 idx: SV_DispatchThreadID)
        {
            texture[idx.xy] = float4(1, 0, 0, 1);
        }
    )";
    ComPtr<ISlangFileSystemExt> fs = ComPtr<ISlangFileSystemExt>(new MemoryFileSystem());
    auto& memoryFS = *static_cast<MemoryFileSystem*>(fs.get());
    memoryFS.saveFile("test.slang", testSource, strlen(testSource));
    memoryFS.saveFile("foo.slang", fooSource, strlen(fooSource));

    ComPtr<ISlangFileSystemExt> precompiledFs = ComPtr<ISlangFileSystemExt>(new MemoryFileSystem());
    auto& memoryPrecompiledFS = *static_cast<MemoryFileSystem*>(precompiledFs.get());

    ComPtr<slang::IGlobalSession> globalSession;
    SLANG_CHECK_ABORT(
        slang_createGlobalSession(SLANG_API_VERSION, globalSession.writeRef()) == SLANG_OK);

    slang::SessionDesc sessionDesc = {};
    sessionDesc.targetCount = 1;
    slang::TargetDesc targetDesc = {};
    targetDesc.format = SLANG_SPIRV;
    targetDesc.profile = globalSession->findProfile("spirv_1_5");
    sessionDesc.targets = &targetDesc;

    // Phase 1: load debug module and save precompiled IR modules.
    {
        ComPtr<slang::ISession> session;
        sessionDesc.fileSystem = fs;
        SLANG_CHECK_ABORT(
            globalSession->createSession(sessionDesc, session.writeRef()) == SLANG_OK);
        ComPtr<ISlangBlob> diagnostics;

        auto testModule = session->loadModule("test", diagnostics.writeRef());

        SLANG_CHECK_ABORT(testModule != nullptr);
        if (diagnostics)
        {
            // If there are diagnostics, they should be warnings or errors
            SLANG_CHECK_ABORT(diagnostics->getBufferSize() > 0);
        }

        for (int i = 0; i < session->getLoadedModuleCount(); i++)
        {
            slang::IModule* mod = session->getLoadedModule(i);
            String path = (StringBuilder() << mod->getFilePath() << "-module");

            ComPtr<slang::IBlob> serializedBlob;
            SLANG_CHECK_ABORT(mod->serialize(serializedBlob.writeRef()) == SLANG_OK);
            memoryPrecompiledFS.saveFileBlob(path.getBuffer(), serializedBlob);
        }
    }

    // Phase 2: Create a new session and load from precompiled modules.
    {
        ComPtr<slang::ISession> session;
        sessionDesc.fileSystem = precompiledFs;
        SLANG_CHECK_ABORT(
            globalSession->createSession(sessionDesc, session.writeRef()) == SLANG_OK);
        ComPtr<ISlangBlob> diagnostics;
        auto module = session->loadModule("test", diagnostics.writeRef());
        SLANG_CHECK_ABORT(module != nullptr);

        // Generate code.
        ComPtr<slang::IEntryPoint> entryPoint;
        module->findEntryPointByName("computeMain", entryPoint.writeRef());
        SLANG_CHECK_ABORT(entryPoint != nullptr);
        ComPtr<slang::IComponentType> linkedProgram;
        entryPoint->link(linkedProgram.writeRef());
        SLANG_CHECK_ABORT(linkedProgram != nullptr);
        ComPtr<ISlangBlob> code;
        linkedProgram->getEntryPointCode(0, 0, code.writeRef());
        SLANG_CHECK_ABORT(code != nullptr);
        auto codeStr =
            UnownedStringSlice((const char*)code->getBufferPointer(), code->getBufferSize());
        SLANG_CHECK(codeStr.indexOf(toSlice("computeMain")) != -1);
    }
}
```

**Comment by csyonghe** [comment]
Ah, I see the problem is when you have `test.slang-module` but not `foo.slang-module`. The load failed when mixing `foo.slang` (source) and `test.slang-module` (precompiled module).

This source reproduces the same issue:

```
// unit-test-precompiled-module-attribute.cpp

// Test loading a precompiled module that defines a user defined attribute.

#include "core/slang-io.h"
#include "core/slang-memory-file-system.h"
#include "slang-com-ptr.h"
#include "slang.h"
#include "unit-test/slang-unit-test.h"

#include <stdio.h>
#include <stdlib.h>

using namespace Slang;

// Test loading a precompiled module that imports other modules.
SLANG_UNIT_TEST(precompiledModuleWithUserDefinedAttribute)
{
    // Prepare the virtual file system with the module files.
    const char* fooSource = R"(
        module foo;
        [__AttributeUsage(_AttributeTargets.Var)]
        public struct TextureAttribute
        {
            string name;
        };
    )";
    const char* testSource = R"(
        module test;
        import foo;

        [Texture("myTextureName")]
        RWTexture2D texture;

        [numthreads(1, 1, 1)]
        void computeMain(uint3 idx: SV_DispatchThreadID)
        {
            texture[idx.xy] = float4(1, 0, 0, 1);
        }
    )";
    ComPtr<ISlangFileSystemExt> fs = ComPtr<ISlangFileSystemExt>(new MemoryFileSystem());
    auto& memoryFS = *static_cast<MemoryFileSystem*>(fs.get());
    memoryFS.saveFile("test.slang", testSource, strlen(testSource));
    memoryFS.saveFile("foo.slang", fooSource, strlen(fooSource));

    // `precompiledFs` will hold `test.slang-module` (precompiled) and `foo.slang` (source).
    ComPtr<ISlangFileSystemExt> precompiledFs = ComPtr<ISlangFileSystemExt>(new MemoryFileSystem());
    auto& memoryPrecompiledFS = *static_cast<MemoryFileSystem*>(precompiledFs.get());

    memoryPrecompiledFS.saveFile("foo.slang", fooSource, strlen(fooSource));

    ComPtr<slang::IGlobalSession> globalSession;
    SLANG_CHECK_ABORT(
        slang_createGlobalSession(SLANG_API_VERSION, globalSession.writeRef()) == SLANG_OK);

    slang::SessionDesc sessionDesc = {};
    sessionDesc.targetCount = 1;
    slang::TargetDesc targetDesc = {};
    targetDesc.format = SLANG_SPIRV;
    targetDesc.profile = globalSession->findProfile("spirv_1_5");
    sessionDesc.targets = &targetDesc;

    // Phase 1: load debug module and save precompiled IR modules.
    {
        ComPtr<slang::ISession> session;
        sessionDesc.fileSystem = fs;
        SLANG_CHECK_ABORT(
            globalSession->createSession(sessionDesc, session.writeRef()) == SLANG_OK);
        ComPtr<ISlangBlob> diagnostics;

        auto testModule = session->loadModule("test", diagnostics.writeRef());

        SLANG_CHECK_ABORT(testModule != nullptr);
        if (diagnostics)
        {
            // If there are diagnostics, they should be warnings or errors
            SLANG_CHECK_ABORT(diagnostics->getBufferSize() > 0);
        }

        for (int i = 0; i < session->getLoadedModuleCount(); i++)
        {
            slang::IModule* mod = session->getLoadedModule(i);

            String path = (StringBuilder() << mod->getFilePath() << "-module");
            if (path == "test.slang-module")
            {
                // Save only `test.slang-module` as precompiled module.
                ComPtr<slang::IBlob> serializedBlob;
                SLANG_CHECK_ABORT(mod->serialize(serializedBlob.writeRef()) == SLANG_OK);
                memoryPrecompiledFS.saveFileBlob(path.getBuffer(), serializedBlob);
            }
        }
    }


    // Phase 2: Create a new session and load from precompiled modules.
    {
        ComPtr<slang::ISession> session;
        sessionDesc.fileSystem = precompiledFs;
        SLANG_CHECK_ABORT(
            globalSession->createSession(sessionDesc, session.writeRef()) == SLANG_OK);
        ComPtr<ISlangBlob> diagnostics;
        auto module = session->loadModule("test", diagnostics.writeRef());
        SLANG_CHECK_ABORT(module != nullptr);

        // Generate code.
        ComPtr<slang::IEntryPoint> entryPoint;
        module->findEntryPointByName("computeMain", entryPoint.writeRef());
        SLANG_CHECK_ABORT(entryPoint != nullptr);
        ComPtr<slang::IComponentType> linkedProgram;
        entryPoint->link(linkedProgram.writeRef());
        SLANG_CHECK_ABORT(linkedProgram != nullptr);
        ComPtr<ISlangBlob> code;
        linkedProgram->getEntryPointCode(0, 0, code.writeRef());
        SLANG_CHECK_ABORT(code != nullptr);
        auto codeStr =
            UnownedStringSlice((const char*)code->getBufferPointer(), code->getBufferSize());
        SLANG_CHECK(codeStr.indexOf(toSlice("computeMain")) != -1);
    }
}
```

**Comment by csyonghe** [comment]
OK, this should be fixed with PR #9481. The root cause is very nuanced. Thank you again for providing this repro!

**Comment by AlpyneDreams** [comment]
> OK, this should be fixed with PR [#9481](https://github.com/shader-slang/slang/pull/9481). The root cause is very nuanced. Thank you again for providing this repro!

Awesome, thanks! Happy to help

**Comment by AlpyneDreams** [comment]
> Ah, I see the problem is when you have `test.slang-module` but not `foo.slang-module`. The load failed when mixing `foo.slang` (source) and `test.slang-module` (precompiled module).

Yeah I think this was particularly exacerbated by some combination of `UseUpToDateBinaryModule` and some include path issues causing that to happen even if a full folder of slang-modules was baked.
